# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#
name: Tests

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/docs.yml"
  push:
    paths-ignore:
      - "docs/**"
      - "**/docs.yml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
    tags: ["**"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        node-version: ["16"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node-version }}"

      - name: git version
        run: git --version

      - name: Run webpack to build static assets
        run: |
          npm install
          npm run webpack

      - name: Install dependencies
        run: |
          pip install -r dev-requirements.txt
          pip install .
          pip freeze

      - name: Run tests
        run: |
          pytest --verbose --maxfail=2 --color=yes --cov nbgitpuller
